services:
 backend:
  build: .
  container_name: django_backend
  env_file:
   - .env
  ports:
   - '8000:10000'
  depends_on:
   - db
  volumes:
   - .:/app
  environment:
   - DJANGO_ENV=${DJANGO_ENV}

 db:
  image: postgres:15
  container_name: postgres_db
  restart: always
  environment:
   POSTGRES_DB: ${POSTGRES_DB}
   POSTGRES_USER: ${POSTGRES_USER}
   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   POSTGRES_HOST_AUTH_METHOD: trust
  ports:
   - '5432:5432'
  volumes:
   - postgres_data:/var/lib/postgresql/data

 rabbitmq:
  image: rabbitmq:3-management
  container_name: discussion_forum_rabbitmq
  restart: always
  ports:
   - '5672:5672'
   - '15672:15672'
  environment:
   RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
   RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

 celery:
  build:
   context: .
   dockerfile: Dockerfile
  container_name: discussion_forum_celery
  env_file:
   - .env
  command: celery -A config worker --loglevel=info
  environment:
   CELERY_BROKER_URL: ${CELERY_BROKER_URL}
  depends_on:
   - backend
   - rabbitmq
  volumes:
   - .:/app

 sonarqube:
  image: sonarqube:lts
  container_name: sonarqube
  depends_on:
   - sonarqube_db
  ports:
   - '9000:9000'
  environment:
   SONAR_JDBC_URL: jdbc:postgresql://sonarqube_db:5432/sonarqube
   SONAR_JDBC_USERNAME: sonar
   SONAR_JDBC_PASSWORD: sonar
  volumes:
   - sonarqube_data:/opt/sonarqube/data
   - sonarqube_logs:/opt/sonarqube/logs
   - sonarqube_extensions:/opt/sonarqube/extensions
  networks:
   - sonarnet

 sonarqube_db:
  image: postgres:15
  container_name: sonarqube_postgres
  restart: always
  environment:
   POSTGRES_DB: sonarqube
   POSTGRES_USER: sonar
   POSTGRES_PASSWORD: sonar
  volumes:
   - sonarqube_db_data:/var/lib/postgresql/data
  networks:
   - sonarnet

volumes:
 postgres_data:
 sonarqube_data:
 sonarqube_logs:
 sonarqube_extensions:
 sonarqube_db_data:

networks:
 sonarnet:
