# Generated by Django 5.1.6 on 2025-03-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatarUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
