# Generated by Django 5.1.6 on 2025-03-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_avatarurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='avatarUrl',
            new_name='avatar_url',
        ),
    ]
